{% set name = "geoapis" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoapis-{{ version }}.tar.gz
  sha256: b0306f769fd40dfd8d9a436e9fabf5687d92bca2604e02ef697e4c37e3665461

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - boto3
    - geopandas >=0.10
    - python >=3.7
    - python-dotenv
    - requests
    - tomli

test:
  imports:
    - geoapis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/geoapis/
  summary: A package for downloading geospatial data from web APIs.
  description: |
    geoapis is a Python package for simply downloading publicly available
    web-hosted geo-spatial data. It currently supports downloading LiDAR data
    from OpenTopography, and vector or raster data from the LINZ Data Service.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rosepearson
